//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::chat::Entity as Chat;
pub use super::posts::Entity as Posts;
pub use super::topics::Entity as Topics;
pub use super::users::Entity as Users;
